/**
 * mining_l2.hpp — Hot path for L=2 pattern mining.
 */
#pragma once

#include "mining.hpp"

namespace hugiml {

/// Extended "augmented_patterns" hot path: identical to mine_patterns_l2_cpp
/// except that items whose source column (td.item_col[item-1]) is listed in
/// relaxed_cols bypass every G-based and RIU/TWU-seed-based gate so they are
/// still mined and can combine with any other item in ordinary L=2 pairing,
/// even when their own information gain does not clear G. Non-relaxed items
/// are gated exactly as in mine_patterns_l2_cpp. No augmented-pair operator
/// features (sum/product/etc.) are generated by this path; relaxed source
/// columns are simply admitted into native L=2 mining as ordinary items.
///
/// Budget contract: relaxed_quota is a CARVE-OUT of K, not an addition.
/// ordinary_K = K - relaxed_quota; relaxed_quota slots are reserved for an
/// IG-ranked heap of patterns that touch at least one relaxed item, so
/// |patterns| + |relaxed_patterns| <= K always. Routing between the two
/// heaps is mutually exclusive (a pattern touching a relaxed item goes only
/// to relaxed_patterns, even if it would also clear G on its own), so no
/// pattern can occupy a slot in both tracks. relaxed_quota=0 (the default)
/// makes this function exactly output-equivalent to mine_patterns_l2_cpp
/// when relaxed_cols is also empty.
///
/// The separate IG-ranked track is necessary, not cosmetic: utility-ranked
/// competition against ordinary high-utility/low-IG patterns was found,
/// empirically, to crowd relaxed survivors out of realistic topK budgets
/// even after the G-gate relaxation succeeded.
struct AugmentedPatternsResult {
    std::vector<PatternEntry> patterns;          // ordinary, utility-ranked, <= K - relaxed_quota
    std::vector<PatternEntry> relaxed_patterns;  // relaxed survivors, IG-ranked, <= relaxed_quota
};

std::vector<PatternEntry> mine_patterns_l2_cpp(
    const TransactionDataCpp& td,
    const std::vector<int>&   ytrain,
    int n_cls, int K, double G,
    double timeout_s = 0.0);

AugmentedPatternsResult mine_patterns_l2_augmented_patterns_cpp(
    const TransactionDataCpp& td,
    const std::vector<int>&   ytrain,
    int n_cls, int K, double G,
    const std::vector<int>&   relaxed_cols,
    int relaxed_quota = 0,
    double timeout_s = 0.0);

/// Variant 2: no relaxed_quota parameter. Both the ordinary (utility-ranked)
/// heap and the relaxed-survivor (IG-ranked) heap run at FULL independent
/// capacity K each, producing up to 2K raw candidates. The two pools are
/// then merged and globally re-ranked by IG, keeping only the final top-K.
/// This trades the carve-out's "reserve N slots up front" approach for
/// "generate generously, then let IG decide what actually survives" --
/// avoiding the extra relaxed_quota parameter and its dataset-dependent
/// tuning, at the cost of mining roughly 2x the candidates internally
/// (still bounded and cheap relative to the L2 hot path's normal cost).
std::vector<PatternEntry> mine_patterns_l2_augmented_patterns_v2_cpp(
    const TransactionDataCpp& td,
    const std::vector<int>&   ytrain,
    int n_cls, int K, double G,
    const std::vector<int>&   relaxed_cols,
    double timeout_s = 0.0);

}  // namespace hugiml
